name: rubocop
on: [pull_request]
jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.7.5
        bundler-cache: true
    - run: |
        gem install bundler
        bundle install
      working-directory: ./backend
    - uses: reviewdog/action-setup@v1
      with:
        reviewdog_version: latest
    - name: Run rubocop with reviewdog
      env:
        REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: bundle exec rubocop | reviewdog -reporter=github-pr-review -f=rubocop
      working-directory: ./backend
