name: rubocop
on: [pull_request]
jobs:
  rubocop:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.5
        bundler-cache: true
        #    - run: |
        #        gem install bundler
        #        bundle config set path 'vendor/bundle'
        #        bundle install --jobs 4 --retry 3
        #    - uses: reviewdog/action-setup@v1
        #      with:
        #        reviewdog_version: latest
    - name: rubocop
      uses: reviewdog/action-rubocop@v2
      with:
        rubocop_version: gemfile
        rubocop_extensions: rubocop-rails:gemfile rubocop-performance:gemfile
        rubocop_flags: backend/
        level: warning
        reporter: github-pr-review
        workdir: ./backend

